/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.performance_schema.tables;


import com.neurasim.jooq.performance_schema.Keys;
import com.neurasim.jooq.performance_schema.PerformanceSchema;
import com.neurasim.jooq.performance_schema.enums.SetupMetersEnabled;
import com.neurasim.jooq.performance_schema.tables.records.SetupMetersRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetupMeters extends TableImpl<SetupMetersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>performance_schema.setup_meters</code>
     */
    public static final SetupMeters SETUP_METERS = new SetupMeters();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SetupMetersRecord> getRecordType() {
        return SetupMetersRecord.class;
    }

    /**
     * The column <code>performance_schema.setup_meters.NAME</code>.
     */
    public final TableField<SetupMetersRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(63).nullable(false), this, "");

    /**
     * The column <code>performance_schema.setup_meters.FREQUENCY</code>.
     */
    public final TableField<SetupMetersRecord, UInteger> FREQUENCY = createField(DSL.name("FREQUENCY"), SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>performance_schema.setup_meters.ENABLED</code>.
     */
    public final TableField<SetupMetersRecord, SetupMetersEnabled> ENABLED = createField(DSL.name("ENABLED"), SQLDataType.VARCHAR(3).nullable(false).asEnumDataType(com.neurasim.jooq.performance_schema.enums.SetupMetersEnabled.class), this, "");

    /**
     * The column <code>performance_schema.setup_meters.DESCRIPTION</code>.
     */
    public final TableField<SetupMetersRecord, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), SQLDataType.VARCHAR(1023), this, "");

    private SetupMeters(Name alias, Table<SetupMetersRecord> aliased) {
        this(alias, aliased, null);
    }

    private SetupMeters(Name alias, Table<SetupMetersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>performance_schema.setup_meters</code> table
     * reference
     */
    public SetupMeters(String alias) {
        this(DSL.name(alias), SETUP_METERS);
    }

    /**
     * Create an aliased <code>performance_schema.setup_meters</code> table
     * reference
     */
    public SetupMeters(Name alias) {
        this(alias, SETUP_METERS);
    }

    /**
     * Create a <code>performance_schema.setup_meters</code> table reference
     */
    public SetupMeters() {
        this(DSL.name("setup_meters"), null);
    }

    public <O extends Record> SetupMeters(Table<O> child, ForeignKey<O, SetupMetersRecord> key) {
        super(child, key, SETUP_METERS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : PerformanceSchema.PERFORMANCE_SCHEMA;
    }

    @Override
    public UniqueKey<SetupMetersRecord> getPrimaryKey() {
        return Keys.KEY_SETUP_METERS_PRIMARY;
    }

    @Override
    public SetupMeters as(String alias) {
        return new SetupMeters(DSL.name(alias), this);
    }

    @Override
    public SetupMeters as(Name alias) {
        return new SetupMeters(alias, this);
    }

    @Override
    public SetupMeters as(Table<?> alias) {
        return new SetupMeters(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SetupMeters rename(String name) {
        return new SetupMeters(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SetupMeters rename(Name name) {
        return new SetupMeters(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SetupMeters rename(Table<?> name) {
        return new SetupMeters(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, UInteger, SetupMetersEnabled, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super String, ? super UInteger, ? super SetupMetersEnabled, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super String, ? super UInteger, ? super SetupMetersEnabled, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
