/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.user_task_management.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum TaskStatus implements EnumType {

    PENDING("PENDING"),

    IN_PROGRESS("IN_PROGRESS"),

    COMPLETED("COMPLETED");

    private final String literal;

    private TaskStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "Task_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static TaskStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(TaskStatus.class, literal);
    }
}
