/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.performance_schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GlobalVariableAttributes implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String variableName;
    private final String attrName;
    private final String attrValue;

    public GlobalVariableAttributes(GlobalVariableAttributes value) {
        this.variableName = value.variableName;
        this.attrName = value.attrName;
        this.attrValue = value.attrValue;
    }

    public GlobalVariableAttributes(
        String variableName,
        String attrName,
        String attrValue
    ) {
        this.variableName = variableName;
        this.attrName = attrName;
        this.attrValue = attrValue;
    }

    /**
     * Getter for
     * <code>performance_schema.global_variable_attributes.VARIABLE_NAME</code>.
     */
    public String getVariableName() {
        return this.variableName;
    }

    /**
     * Getter for
     * <code>performance_schema.global_variable_attributes.ATTR_NAME</code>.
     */
    public String getAttrName() {
        return this.attrName;
    }

    /**
     * Getter for
     * <code>performance_schema.global_variable_attributes.ATTR_VALUE</code>.
     */
    public String getAttrValue() {
        return this.attrValue;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GlobalVariableAttributes other = (GlobalVariableAttributes) obj;
        if (this.variableName == null) {
            if (other.variableName != null)
                return false;
        }
        else if (!this.variableName.equals(other.variableName))
            return false;
        if (this.attrName == null) {
            if (other.attrName != null)
                return false;
        }
        else if (!this.attrName.equals(other.attrName))
            return false;
        if (this.attrValue == null) {
            if (other.attrValue != null)
                return false;
        }
        else if (!this.attrValue.equals(other.attrValue))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.variableName == null) ? 0 : this.variableName.hashCode());
        result = prime * result + ((this.attrName == null) ? 0 : this.attrName.hashCode());
        result = prime * result + ((this.attrValue == null) ? 0 : this.attrValue.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GlobalVariableAttributes (");

        sb.append(variableName);
        sb.append(", ").append(attrName);
        sb.append(", ").append(attrValue);

        sb.append(")");
        return sb.toString();
    }
}
