/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.performance_schema.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetadataLocks implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String objectType;
    private final String objectSchema;
    private final String objectName;
    private final String columnName;
    private final ULong objectInstanceBegin;
    private final String lockType;
    private final String lockDuration;
    private final String lockStatus;
    private final String source;
    private final ULong ownerThreadId;
    private final ULong ownerEventId;

    public MetadataLocks(MetadataLocks value) {
        this.objectType = value.objectType;
        this.objectSchema = value.objectSchema;
        this.objectName = value.objectName;
        this.columnName = value.columnName;
        this.objectInstanceBegin = value.objectInstanceBegin;
        this.lockType = value.lockType;
        this.lockDuration = value.lockDuration;
        this.lockStatus = value.lockStatus;
        this.source = value.source;
        this.ownerThreadId = value.ownerThreadId;
        this.ownerEventId = value.ownerEventId;
    }

    public MetadataLocks(
        String objectType,
        String objectSchema,
        String objectName,
        String columnName,
        ULong objectInstanceBegin,
        String lockType,
        String lockDuration,
        String lockStatus,
        String source,
        ULong ownerThreadId,
        ULong ownerEventId
    ) {
        this.objectType = objectType;
        this.objectSchema = objectSchema;
        this.objectName = objectName;
        this.columnName = columnName;
        this.objectInstanceBegin = objectInstanceBegin;
        this.lockType = lockType;
        this.lockDuration = lockDuration;
        this.lockStatus = lockStatus;
        this.source = source;
        this.ownerThreadId = ownerThreadId;
        this.ownerEventId = ownerEventId;
    }

    /**
     * Getter for <code>performance_schema.metadata_locks.OBJECT_TYPE</code>.
     */
    public String getObjectType() {
        return this.objectType;
    }

    /**
     * Getter for <code>performance_schema.metadata_locks.OBJECT_SCHEMA</code>.
     */
    public String getObjectSchema() {
        return this.objectSchema;
    }

    /**
     * Getter for <code>performance_schema.metadata_locks.OBJECT_NAME</code>.
     */
    public String getObjectName() {
        return this.objectName;
    }

    /**
     * Getter for <code>performance_schema.metadata_locks.COLUMN_NAME</code>.
     */
    public String getColumnName() {
        return this.columnName;
    }

    /**
     * Getter for
     * <code>performance_schema.metadata_locks.OBJECT_INSTANCE_BEGIN</code>.
     */
    public ULong getObjectInstanceBegin() {
        return this.objectInstanceBegin;
    }

    /**
     * Getter for <code>performance_schema.metadata_locks.LOCK_TYPE</code>.
     */
    public String getLockType() {
        return this.lockType;
    }

    /**
     * Getter for <code>performance_schema.metadata_locks.LOCK_DURATION</code>.
     */
    public String getLockDuration() {
        return this.lockDuration;
    }

    /**
     * Getter for <code>performance_schema.metadata_locks.LOCK_STATUS</code>.
     */
    public String getLockStatus() {
        return this.lockStatus;
    }

    /**
     * Getter for <code>performance_schema.metadata_locks.SOURCE</code>.
     */
    public String getSource() {
        return this.source;
    }

    /**
     * Getter for
     * <code>performance_schema.metadata_locks.OWNER_THREAD_ID</code>.
     */
    public ULong getOwnerThreadId() {
        return this.ownerThreadId;
    }

    /**
     * Getter for <code>performance_schema.metadata_locks.OWNER_EVENT_ID</code>.
     */
    public ULong getOwnerEventId() {
        return this.ownerEventId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MetadataLocks other = (MetadataLocks) obj;
        if (this.objectType == null) {
            if (other.objectType != null)
                return false;
        }
        else if (!this.objectType.equals(other.objectType))
            return false;
        if (this.objectSchema == null) {
            if (other.objectSchema != null)
                return false;
        }
        else if (!this.objectSchema.equals(other.objectSchema))
            return false;
        if (this.objectName == null) {
            if (other.objectName != null)
                return false;
        }
        else if (!this.objectName.equals(other.objectName))
            return false;
        if (this.columnName == null) {
            if (other.columnName != null)
                return false;
        }
        else if (!this.columnName.equals(other.columnName))
            return false;
        if (this.objectInstanceBegin == null) {
            if (other.objectInstanceBegin != null)
                return false;
        }
        else if (!this.objectInstanceBegin.equals(other.objectInstanceBegin))
            return false;
        if (this.lockType == null) {
            if (other.lockType != null)
                return false;
        }
        else if (!this.lockType.equals(other.lockType))
            return false;
        if (this.lockDuration == null) {
            if (other.lockDuration != null)
                return false;
        }
        else if (!this.lockDuration.equals(other.lockDuration))
            return false;
        if (this.lockStatus == null) {
            if (other.lockStatus != null)
                return false;
        }
        else if (!this.lockStatus.equals(other.lockStatus))
            return false;
        if (this.source == null) {
            if (other.source != null)
                return false;
        }
        else if (!this.source.equals(other.source))
            return false;
        if (this.ownerThreadId == null) {
            if (other.ownerThreadId != null)
                return false;
        }
        else if (!this.ownerThreadId.equals(other.ownerThreadId))
            return false;
        if (this.ownerEventId == null) {
            if (other.ownerEventId != null)
                return false;
        }
        else if (!this.ownerEventId.equals(other.ownerEventId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.objectType == null) ? 0 : this.objectType.hashCode());
        result = prime * result + ((this.objectSchema == null) ? 0 : this.objectSchema.hashCode());
        result = prime * result + ((this.objectName == null) ? 0 : this.objectName.hashCode());
        result = prime * result + ((this.columnName == null) ? 0 : this.columnName.hashCode());
        result = prime * result + ((this.objectInstanceBegin == null) ? 0 : this.objectInstanceBegin.hashCode());
        result = prime * result + ((this.lockType == null) ? 0 : this.lockType.hashCode());
        result = prime * result + ((this.lockDuration == null) ? 0 : this.lockDuration.hashCode());
        result = prime * result + ((this.lockStatus == null) ? 0 : this.lockStatus.hashCode());
        result = prime * result + ((this.source == null) ? 0 : this.source.hashCode());
        result = prime * result + ((this.ownerThreadId == null) ? 0 : this.ownerThreadId.hashCode());
        result = prime * result + ((this.ownerEventId == null) ? 0 : this.ownerEventId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MetadataLocks (");

        sb.append(objectType);
        sb.append(", ").append(objectSchema);
        sb.append(", ").append(objectName);
        sb.append(", ").append(columnName);
        sb.append(", ").append(objectInstanceBegin);
        sb.append(", ").append(lockType);
        sb.append(", ").append(lockDuration);
        sb.append(", ").append(lockStatus);
        sb.append(", ").append(source);
        sb.append(", ").append(ownerThreadId);
        sb.append(", ").append(ownerEventId);

        sb.append(")");
        return sb.toString();
    }
}
