/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.performance_schema.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionConnectAttrs implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong processlistId;
    private final String attrName;
    private final String attrValue;
    private final Integer ordinalPosition;

    public SessionConnectAttrs(SessionConnectAttrs value) {
        this.processlistId = value.processlistId;
        this.attrName = value.attrName;
        this.attrValue = value.attrValue;
        this.ordinalPosition = value.ordinalPosition;
    }

    public SessionConnectAttrs(
        ULong processlistId,
        String attrName,
        String attrValue,
        Integer ordinalPosition
    ) {
        this.processlistId = processlistId;
        this.attrName = attrName;
        this.attrValue = attrValue;
        this.ordinalPosition = ordinalPosition;
    }

    /**
     * Getter for
     * <code>performance_schema.session_connect_attrs.PROCESSLIST_ID</code>.
     */
    public ULong getProcesslistId() {
        return this.processlistId;
    }

    /**
     * Getter for
     * <code>performance_schema.session_connect_attrs.ATTR_NAME</code>.
     */
    public String getAttrName() {
        return this.attrName;
    }

    /**
     * Getter for
     * <code>performance_schema.session_connect_attrs.ATTR_VALUE</code>.
     */
    public String getAttrValue() {
        return this.attrValue;
    }

    /**
     * Getter for
     * <code>performance_schema.session_connect_attrs.ORDINAL_POSITION</code>.
     */
    public Integer getOrdinalPosition() {
        return this.ordinalPosition;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SessionConnectAttrs other = (SessionConnectAttrs) obj;
        if (this.processlistId == null) {
            if (other.processlistId != null)
                return false;
        }
        else if (!this.processlistId.equals(other.processlistId))
            return false;
        if (this.attrName == null) {
            if (other.attrName != null)
                return false;
        }
        else if (!this.attrName.equals(other.attrName))
            return false;
        if (this.attrValue == null) {
            if (other.attrValue != null)
                return false;
        }
        else if (!this.attrValue.equals(other.attrValue))
            return false;
        if (this.ordinalPosition == null) {
            if (other.ordinalPosition != null)
                return false;
        }
        else if (!this.ordinalPosition.equals(other.ordinalPosition))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.processlistId == null) ? 0 : this.processlistId.hashCode());
        result = prime * result + ((this.attrName == null) ? 0 : this.attrName.hashCode());
        result = prime * result + ((this.attrValue == null) ? 0 : this.attrValue.hashCode());
        result = prime * result + ((this.ordinalPosition == null) ? 0 : this.ordinalPosition.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SessionConnectAttrs (");

        sb.append(processlistId);
        sb.append(", ").append(attrName);
        sb.append(", ").append(attrValue);
        sb.append(", ").append(ordinalPosition);

        sb.append(")");
        return sb.toString();
    }
}
