/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.performance_schema.tables.pojos;


import com.neurasim.jooq.performance_schema.enums.SetupLoggersLevel;

import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetupLoggers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String name;
    private final SetupLoggersLevel level;
    private final String description;

    public SetupLoggers(SetupLoggers value) {
        this.name = value.name;
        this.level = value.level;
        this.description = value.description;
    }

    public SetupLoggers(
        String name,
        SetupLoggersLevel level,
        String description
    ) {
        this.name = name;
        this.level = level;
        this.description = description;
    }

    /**
     * Getter for <code>performance_schema.setup_loggers.NAME</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>performance_schema.setup_loggers.LEVEL</code>.
     */
    public SetupLoggersLevel getLevel() {
        return this.level;
    }

    /**
     * Getter for <code>performance_schema.setup_loggers.DESCRIPTION</code>.
     */
    public String getDescription() {
        return this.description;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SetupLoggers other = (SetupLoggers) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.level == null) {
            if (other.level != null)
                return false;
        }
        else if (!this.level.equals(other.level))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.level == null) ? 0 : this.level.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SetupLoggers (");

        sb.append(name);
        sb.append(", ").append(level);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
