/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.performance_schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusByAccount implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String user;
    private final String host;
    private final String variableName;
    private final String variableValue;

    public StatusByAccount(StatusByAccount value) {
        this.user = value.user;
        this.host = value.host;
        this.variableName = value.variableName;
        this.variableValue = value.variableValue;
    }

    public StatusByAccount(
        String user,
        String host,
        String variableName,
        String variableValue
    ) {
        this.user = user;
        this.host = host;
        this.variableName = variableName;
        this.variableValue = variableValue;
    }

    /**
     * Getter for <code>performance_schema.status_by_account.USER</code>.
     */
    public String getUser() {
        return this.user;
    }

    /**
     * Getter for <code>performance_schema.status_by_account.HOST</code>.
     */
    public String getHost() {
        return this.host;
    }

    /**
     * Getter for
     * <code>performance_schema.status_by_account.VARIABLE_NAME</code>.
     */
    public String getVariableName() {
        return this.variableName;
    }

    /**
     * Getter for
     * <code>performance_schema.status_by_account.VARIABLE_VALUE</code>.
     */
    public String getVariableValue() {
        return this.variableValue;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final StatusByAccount other = (StatusByAccount) obj;
        if (this.user == null) {
            if (other.user != null)
                return false;
        }
        else if (!this.user.equals(other.user))
            return false;
        if (this.host == null) {
            if (other.host != null)
                return false;
        }
        else if (!this.host.equals(other.host))
            return false;
        if (this.variableName == null) {
            if (other.variableName != null)
                return false;
        }
        else if (!this.variableName.equals(other.variableName))
            return false;
        if (this.variableValue == null) {
            if (other.variableValue != null)
                return false;
        }
        else if (!this.variableValue.equals(other.variableValue))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.user == null) ? 0 : this.user.hashCode());
        result = prime * result + ((this.host == null) ? 0 : this.host.hashCode());
        result = prime * result + ((this.variableName == null) ? 0 : this.variableName.hashCode());
        result = prime * result + ((this.variableValue == null) ? 0 : this.variableValue.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StatusByAccount (");

        sb.append(user);
        sb.append(", ").append(host);
        sb.append(", ").append(variableName);
        sb.append(", ").append(variableValue);

        sb.append(")");
        return sb.toString();
    }
}
