/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.performance_schema.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum VariablesMetadataDataType implements EnumType {

    Integer("Integer"),

    Numeric("Numeric"),

    String("String"),

    Enumeration("Enumeration"),

    Boolean("Boolean"),

    Set("Set");

    private final String literal;

    private VariablesMetadataDataType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "variables_metadata_DATA_TYPE";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static VariablesMetadataDataType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(VariablesMetadataDataType.class, literal);
    }
}
