/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.performance_schema.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum VariablesMetadataVariableScope implements EnumType {

    GLOBAL("GLOBAL"),

    SESSION("SESSION"),

    SESSION_ONLY("SESSION_ONLY");

    private final String literal;

    private VariablesMetadataVariableScope(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "variables_metadata_VARIABLE_SCOPE";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static VariablesMetadataVariableScope lookupLiteral(String literal) {
        return EnumType.lookupLiteral(VariablesMetadataVariableScope.class, literal);
    }
}
