/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.mysql.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * The group configuration version.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReplicationGroupConfigurationVersion implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String name;
    private final ULong version;

    public ReplicationGroupConfigurationVersion(ReplicationGroupConfigurationVersion value) {
        this.name = value.name;
        this.version = value.version;
    }

    public ReplicationGroupConfigurationVersion(
        String name,
        ULong version
    ) {
        this.name = name;
        this.version = version;
    }

    /**
     * Getter for
     * <code>mysql.replication_group_configuration_version.name</code>. The
     * configuration name.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for
     * <code>mysql.replication_group_configuration_version.version</code>. The
     * version of the configuration name.
     */
    public ULong getVersion() {
        return this.version;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReplicationGroupConfigurationVersion other = (ReplicationGroupConfigurationVersion) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReplicationGroupConfigurationVersion (");

        sb.append(name);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
