/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.performance_schema.tables.records;


import com.neurasim.jooq.performance_schema.tables.MemorySummaryGlobalByEventName;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemorySummaryGlobalByEventNameRecord extends UpdatableRecordImpl<MemorySummaryGlobalByEventNameRecord> implements Record11<String, ULong, ULong, ULong, ULong, Long, Long, Long, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>performance_schema.memory_summary_global_by_event_name.EVENT_NAME</code>.
     */
    public MemorySummaryGlobalByEventNameRecord setEventName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.memory_summary_global_by_event_name.EVENT_NAME</code>.
     */
    public String getEventName() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>performance_schema.memory_summary_global_by_event_name.COUNT_ALLOC</code>.
     */
    public MemorySummaryGlobalByEventNameRecord setCountAlloc(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.memory_summary_global_by_event_name.COUNT_ALLOC</code>.
     */
    public ULong getCountAlloc() {
        return (ULong) get(1);
    }

    /**
     * Setter for
     * <code>performance_schema.memory_summary_global_by_event_name.COUNT_FREE</code>.
     */
    public MemorySummaryGlobalByEventNameRecord setCountFree(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.memory_summary_global_by_event_name.COUNT_FREE</code>.
     */
    public ULong getCountFree() {
        return (ULong) get(2);
    }

    /**
     * Setter for
     * <code>performance_schema.memory_summary_global_by_event_name.SUM_NUMBER_OF_BYTES_ALLOC</code>.
     */
    public MemorySummaryGlobalByEventNameRecord setSumNumberOfBytesAlloc(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.memory_summary_global_by_event_name.SUM_NUMBER_OF_BYTES_ALLOC</code>.
     */
    public ULong getSumNumberOfBytesAlloc() {
        return (ULong) get(3);
    }

    /**
     * Setter for
     * <code>performance_schema.memory_summary_global_by_event_name.SUM_NUMBER_OF_BYTES_FREE</code>.
     */
    public MemorySummaryGlobalByEventNameRecord setSumNumberOfBytesFree(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.memory_summary_global_by_event_name.SUM_NUMBER_OF_BYTES_FREE</code>.
     */
    public ULong getSumNumberOfBytesFree() {
        return (ULong) get(4);
    }

    /**
     * Setter for
     * <code>performance_schema.memory_summary_global_by_event_name.LOW_COUNT_USED</code>.
     */
    public MemorySummaryGlobalByEventNameRecord setLowCountUsed(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.memory_summary_global_by_event_name.LOW_COUNT_USED</code>.
     */
    public Long getLowCountUsed() {
        return (Long) get(5);
    }

    /**
     * Setter for
     * <code>performance_schema.memory_summary_global_by_event_name.CURRENT_COUNT_USED</code>.
     */
    public MemorySummaryGlobalByEventNameRecord setCurrentCountUsed(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.memory_summary_global_by_event_name.CURRENT_COUNT_USED</code>.
     */
    public Long getCurrentCountUsed() {
        return (Long) get(6);
    }

    /**
     * Setter for
     * <code>performance_schema.memory_summary_global_by_event_name.HIGH_COUNT_USED</code>.
     */
    public MemorySummaryGlobalByEventNameRecord setHighCountUsed(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.memory_summary_global_by_event_name.HIGH_COUNT_USED</code>.
     */
    public Long getHighCountUsed() {
        return (Long) get(7);
    }

    /**
     * Setter for
     * <code>performance_schema.memory_summary_global_by_event_name.LOW_NUMBER_OF_BYTES_USED</code>.
     */
    public MemorySummaryGlobalByEventNameRecord setLowNumberOfBytesUsed(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.memory_summary_global_by_event_name.LOW_NUMBER_OF_BYTES_USED</code>.
     */
    public Long getLowNumberOfBytesUsed() {
        return (Long) get(8);
    }

    /**
     * Setter for
     * <code>performance_schema.memory_summary_global_by_event_name.CURRENT_NUMBER_OF_BYTES_USED</code>.
     */
    public MemorySummaryGlobalByEventNameRecord setCurrentNumberOfBytesUsed(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.memory_summary_global_by_event_name.CURRENT_NUMBER_OF_BYTES_USED</code>.
     */
    public Long getCurrentNumberOfBytesUsed() {
        return (Long) get(9);
    }

    /**
     * Setter for
     * <code>performance_schema.memory_summary_global_by_event_name.HIGH_NUMBER_OF_BYTES_USED</code>.
     */
    public MemorySummaryGlobalByEventNameRecord setHighNumberOfBytesUsed(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.memory_summary_global_by_event_name.HIGH_NUMBER_OF_BYTES_USED</code>.
     */
    public Long getHighNumberOfBytesUsed() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, ULong, ULong, ULong, ULong, Long, Long, Long, Long, Long, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<String, ULong, ULong, ULong, ULong, Long, Long, Long, Long, Long, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME.EVENT_NAME;
    }

    @Override
    public Field<ULong> field2() {
        return MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME.COUNT_ALLOC;
    }

    @Override
    public Field<ULong> field3() {
        return MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME.COUNT_FREE;
    }

    @Override
    public Field<ULong> field4() {
        return MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME.SUM_NUMBER_OF_BYTES_ALLOC;
    }

    @Override
    public Field<ULong> field5() {
        return MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME.SUM_NUMBER_OF_BYTES_FREE;
    }

    @Override
    public Field<Long> field6() {
        return MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME.LOW_COUNT_USED;
    }

    @Override
    public Field<Long> field7() {
        return MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME.CURRENT_COUNT_USED;
    }

    @Override
    public Field<Long> field8() {
        return MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME.HIGH_COUNT_USED;
    }

    @Override
    public Field<Long> field9() {
        return MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME.LOW_NUMBER_OF_BYTES_USED;
    }

    @Override
    public Field<Long> field10() {
        return MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME.CURRENT_NUMBER_OF_BYTES_USED;
    }

    @Override
    public Field<Long> field11() {
        return MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME.HIGH_NUMBER_OF_BYTES_USED;
    }

    @Override
    public String component1() {
        return getEventName();
    }

    @Override
    public ULong component2() {
        return getCountAlloc();
    }

    @Override
    public ULong component3() {
        return getCountFree();
    }

    @Override
    public ULong component4() {
        return getSumNumberOfBytesAlloc();
    }

    @Override
    public ULong component5() {
        return getSumNumberOfBytesFree();
    }

    @Override
    public Long component6() {
        return getLowCountUsed();
    }

    @Override
    public Long component7() {
        return getCurrentCountUsed();
    }

    @Override
    public Long component8() {
        return getHighCountUsed();
    }

    @Override
    public Long component9() {
        return getLowNumberOfBytesUsed();
    }

    @Override
    public Long component10() {
        return getCurrentNumberOfBytesUsed();
    }

    @Override
    public Long component11() {
        return getHighNumberOfBytesUsed();
    }

    @Override
    public String value1() {
        return getEventName();
    }

    @Override
    public ULong value2() {
        return getCountAlloc();
    }

    @Override
    public ULong value3() {
        return getCountFree();
    }

    @Override
    public ULong value4() {
        return getSumNumberOfBytesAlloc();
    }

    @Override
    public ULong value5() {
        return getSumNumberOfBytesFree();
    }

    @Override
    public Long value6() {
        return getLowCountUsed();
    }

    @Override
    public Long value7() {
        return getCurrentCountUsed();
    }

    @Override
    public Long value8() {
        return getHighCountUsed();
    }

    @Override
    public Long value9() {
        return getLowNumberOfBytesUsed();
    }

    @Override
    public Long value10() {
        return getCurrentNumberOfBytesUsed();
    }

    @Override
    public Long value11() {
        return getHighNumberOfBytesUsed();
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord value1(String value) {
        setEventName(value);
        return this;
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord value2(ULong value) {
        setCountAlloc(value);
        return this;
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord value3(ULong value) {
        setCountFree(value);
        return this;
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord value4(ULong value) {
        setSumNumberOfBytesAlloc(value);
        return this;
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord value5(ULong value) {
        setSumNumberOfBytesFree(value);
        return this;
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord value6(Long value) {
        setLowCountUsed(value);
        return this;
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord value7(Long value) {
        setCurrentCountUsed(value);
        return this;
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord value8(Long value) {
        setHighCountUsed(value);
        return this;
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord value9(Long value) {
        setLowNumberOfBytesUsed(value);
        return this;
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord value10(Long value) {
        setCurrentNumberOfBytesUsed(value);
        return this;
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord value11(Long value) {
        setHighNumberOfBytesUsed(value);
        return this;
    }

    @Override
    public MemorySummaryGlobalByEventNameRecord values(String value1, ULong value2, ULong value3, ULong value4, ULong value5, Long value6, Long value7, Long value8, Long value9, Long value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MemorySummaryGlobalByEventNameRecord
     */
    public MemorySummaryGlobalByEventNameRecord() {
        super(MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME);
    }

    /**
     * Create a detached, initialised MemorySummaryGlobalByEventNameRecord
     */
    public MemorySummaryGlobalByEventNameRecord(String eventName, ULong countAlloc, ULong countFree, ULong sumNumberOfBytesAlloc, ULong sumNumberOfBytesFree, Long lowCountUsed, Long currentCountUsed, Long highCountUsed, Long lowNumberOfBytesUsed, Long currentNumberOfBytesUsed, Long highNumberOfBytesUsed) {
        super(MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME);

        setEventName(eventName);
        setCountAlloc(countAlloc);
        setCountFree(countFree);
        setSumNumberOfBytesAlloc(sumNumberOfBytesAlloc);
        setSumNumberOfBytesFree(sumNumberOfBytesFree);
        setLowCountUsed(lowCountUsed);
        setCurrentCountUsed(currentCountUsed);
        setHighCountUsed(highCountUsed);
        setLowNumberOfBytesUsed(lowNumberOfBytesUsed);
        setCurrentNumberOfBytesUsed(currentNumberOfBytesUsed);
        setHighNumberOfBytesUsed(highNumberOfBytesUsed);
    }

    /**
     * Create a detached, initialised MemorySummaryGlobalByEventNameRecord
     */
    public MemorySummaryGlobalByEventNameRecord(com.neurasim.jooq.performance_schema.tables.pojos.MemorySummaryGlobalByEventName value) {
        super(MemorySummaryGlobalByEventName.MEMORY_SUMMARY_GLOBAL_BY_EVENT_NAME);

        if (value != null) {
            setEventName(value.getEventName());
            setCountAlloc(value.getCountAlloc());
            setCountFree(value.getCountFree());
            setSumNumberOfBytesAlloc(value.getSumNumberOfBytesAlloc());
            setSumNumberOfBytesFree(value.getSumNumberOfBytesFree());
            setLowCountUsed(value.getLowCountUsed());
            setCurrentCountUsed(value.getCurrentCountUsed());
            setHighCountUsed(value.getHighCountUsed());
            setLowNumberOfBytesUsed(value.getLowNumberOfBytesUsed());
            setCurrentNumberOfBytesUsed(value.getCurrentNumberOfBytesUsed());
            setHighNumberOfBytesUsed(value.getHighNumberOfBytesUsed());
        }
    }
}
