/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.performance_schema.tables.records;


import com.neurasim.jooq.performance_schema.enums.SetupMetricsMetricType;
import com.neurasim.jooq.performance_schema.enums.SetupMetricsNumType;
import com.neurasim.jooq.performance_schema.tables.SetupMetrics;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetupMetricsRecord extends UpdatableRecordImpl<SetupMetricsRecord> implements Record6<String, String, SetupMetricsMetricType, SetupMetricsNumType, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>performance_schema.setup_metrics.NAME</code>.
     */
    public SetupMetricsRecord setName(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>performance_schema.setup_metrics.NAME</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>performance_schema.setup_metrics.METER</code>.
     */
    public SetupMetricsRecord setMeter(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>performance_schema.setup_metrics.METER</code>.
     */
    public String getMeter() {
        return (String) get(1);
    }

    /**
     * Setter for <code>performance_schema.setup_metrics.METRIC_TYPE</code>.
     */
    public SetupMetricsRecord setMetricType(SetupMetricsMetricType value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>performance_schema.setup_metrics.METRIC_TYPE</code>.
     */
    public SetupMetricsMetricType getMetricType() {
        return (SetupMetricsMetricType) get(2);
    }

    /**
     * Setter for <code>performance_schema.setup_metrics.NUM_TYPE</code>.
     */
    public SetupMetricsRecord setNumType(SetupMetricsNumType value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>performance_schema.setup_metrics.NUM_TYPE</code>.
     */
    public SetupMetricsNumType getNumType() {
        return (SetupMetricsNumType) get(3);
    }

    /**
     * Setter for <code>performance_schema.setup_metrics.UNIT</code>.
     */
    public SetupMetricsRecord setUnit(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>performance_schema.setup_metrics.UNIT</code>.
     */
    public String getUnit() {
        return (String) get(4);
    }

    /**
     * Setter for <code>performance_schema.setup_metrics.DESCRIPTION</code>.
     */
    public SetupMetricsRecord setDescription(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>performance_schema.setup_metrics.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, SetupMetricsMetricType, SetupMetricsNumType, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, SetupMetricsMetricType, SetupMetricsNumType, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SetupMetrics.SETUP_METRICS.NAME;
    }

    @Override
    public Field<String> field2() {
        return SetupMetrics.SETUP_METRICS.METER;
    }

    @Override
    public Field<SetupMetricsMetricType> field3() {
        return SetupMetrics.SETUP_METRICS.METRIC_TYPE;
    }

    @Override
    public Field<SetupMetricsNumType> field4() {
        return SetupMetrics.SETUP_METRICS.NUM_TYPE;
    }

    @Override
    public Field<String> field5() {
        return SetupMetrics.SETUP_METRICS.UNIT;
    }

    @Override
    public Field<String> field6() {
        return SetupMetrics.SETUP_METRICS.DESCRIPTION;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String component2() {
        return getMeter();
    }

    @Override
    public SetupMetricsMetricType component3() {
        return getMetricType();
    }

    @Override
    public SetupMetricsNumType component4() {
        return getNumType();
    }

    @Override
    public String component5() {
        return getUnit();
    }

    @Override
    public String component6() {
        return getDescription();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public String value2() {
        return getMeter();
    }

    @Override
    public SetupMetricsMetricType value3() {
        return getMetricType();
    }

    @Override
    public SetupMetricsNumType value4() {
        return getNumType();
    }

    @Override
    public String value5() {
        return getUnit();
    }

    @Override
    public String value6() {
        return getDescription();
    }

    @Override
    public SetupMetricsRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public SetupMetricsRecord value2(String value) {
        setMeter(value);
        return this;
    }

    @Override
    public SetupMetricsRecord value3(SetupMetricsMetricType value) {
        setMetricType(value);
        return this;
    }

    @Override
    public SetupMetricsRecord value4(SetupMetricsNumType value) {
        setNumType(value);
        return this;
    }

    @Override
    public SetupMetricsRecord value5(String value) {
        setUnit(value);
        return this;
    }

    @Override
    public SetupMetricsRecord value6(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SetupMetricsRecord values(String value1, String value2, SetupMetricsMetricType value3, SetupMetricsNumType value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SetupMetricsRecord
     */
    public SetupMetricsRecord() {
        super(SetupMetrics.SETUP_METRICS);
    }

    /**
     * Create a detached, initialised SetupMetricsRecord
     */
    public SetupMetricsRecord(String name, String meter, SetupMetricsMetricType metricType, SetupMetricsNumType numType, String unit, String description) {
        super(SetupMetrics.SETUP_METRICS);

        setName(name);
        setMeter(meter);
        setMetricType(metricType);
        setNumType(numType);
        setUnit(unit);
        setDescription(description);
    }

    /**
     * Create a detached, initialised SetupMetricsRecord
     */
    public SetupMetricsRecord(com.neurasim.jooq.performance_schema.tables.pojos.SetupMetrics value) {
        super(SetupMetrics.SETUP_METRICS);

        if (value != null) {
            setName(value.getName());
            setMeter(value.getMeter());
            setMetricType(value.getMetricType());
            setNumType(value.getNumType());
            setUnit(value.getUnit());
            setDescription(value.getDescription());
        }
    }
}
