/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.performance_schema.tables.records;


import com.neurasim.jooq.performance_schema.tables.TableLockWaitsSummaryByTable;

import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableLockWaitsSummaryByTableRecord extends TableRecordImpl<TableLockWaitsSummaryByTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.OBJECT_TYPE</code>.
     */
    public TableLockWaitsSummaryByTableRecord setObjectType(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.OBJECT_TYPE</code>.
     */
    public String getObjectType() {
        return (String) get(0);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.OBJECT_SCHEMA</code>.
     */
    public TableLockWaitsSummaryByTableRecord setObjectSchema(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.OBJECT_SCHEMA</code>.
     */
    public String getObjectSchema() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.OBJECT_NAME</code>.
     */
    public TableLockWaitsSummaryByTableRecord setObjectName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.OBJECT_NAME</code>.
     */
    public String getObjectName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_STAR</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountStar(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_STAR</code>.
     */
    public ULong getCountStar() {
        return (ULong) get(3);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WAIT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerWait(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WAIT</code>.
     */
    public ULong getSumTimerWait() {
        return (ULong) get(4);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WAIT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerWait(ULong value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WAIT</code>.
     */
    public ULong getMinTimerWait() {
        return (ULong) get(5);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WAIT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerWait(ULong value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WAIT</code>.
     */
    public ULong getAvgTimerWait() {
        return (ULong) get(6);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WAIT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerWait(ULong value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WAIT</code>.
     */
    public ULong getMaxTimerWait() {
        return (ULong) get(7);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountRead(ULong value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ</code>.
     */
    public ULong getCountRead() {
        return (ULong) get(8);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerRead(ULong value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ</code>.
     */
    public ULong getSumTimerRead() {
        return (ULong) get(9);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerRead(ULong value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ</code>.
     */
    public ULong getMinTimerRead() {
        return (ULong) get(10);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerRead(ULong value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ</code>.
     */
    public ULong getAvgTimerRead() {
        return (ULong) get(11);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerRead(ULong value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ</code>.
     */
    public ULong getMaxTimerRead() {
        return (ULong) get(12);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountWrite(ULong value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE</code>.
     */
    public ULong getCountWrite() {
        return (ULong) get(13);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerWrite(ULong value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE</code>.
     */
    public ULong getSumTimerWrite() {
        return (ULong) get(14);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerWrite(ULong value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE</code>.
     */
    public ULong getMinTimerWrite() {
        return (ULong) get(15);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerWrite(ULong value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE</code>.
     */
    public ULong getAvgTimerWrite() {
        return (ULong) get(16);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerWrite(ULong value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE</code>.
     */
    public ULong getMaxTimerWrite() {
        return (ULong) get(17);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_NORMAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountReadNormal(ULong value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_NORMAL</code>.
     */
    public ULong getCountReadNormal() {
        return (ULong) get(18);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_NORMAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerReadNormal(ULong value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_NORMAL</code>.
     */
    public ULong getSumTimerReadNormal() {
        return (ULong) get(19);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_NORMAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerReadNormal(ULong value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_NORMAL</code>.
     */
    public ULong getMinTimerReadNormal() {
        return (ULong) get(20);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_NORMAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerReadNormal(ULong value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_NORMAL</code>.
     */
    public ULong getAvgTimerReadNormal() {
        return (ULong) get(21);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_NORMAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerReadNormal(ULong value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_NORMAL</code>.
     */
    public ULong getMaxTimerReadNormal() {
        return (ULong) get(22);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_WITH_SHARED_LOCKS</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountReadWithSharedLocks(ULong value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_WITH_SHARED_LOCKS</code>.
     */
    public ULong getCountReadWithSharedLocks() {
        return (ULong) get(23);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerReadWithSharedLocks(ULong value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public ULong getSumTimerReadWithSharedLocks() {
        return (ULong) get(24);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerReadWithSharedLocks(ULong value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public ULong getMinTimerReadWithSharedLocks() {
        return (ULong) get(25);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerReadWithSharedLocks(ULong value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public ULong getAvgTimerReadWithSharedLocks() {
        return (ULong) get(26);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerReadWithSharedLocks(ULong value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_WITH_SHARED_LOCKS</code>.
     */
    public ULong getMaxTimerReadWithSharedLocks() {
        return (ULong) get(27);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_HIGH_PRIORITY</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountReadHighPriority(ULong value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_HIGH_PRIORITY</code>.
     */
    public ULong getCountReadHighPriority() {
        return (ULong) get(28);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerReadHighPriority(ULong value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public ULong getSumTimerReadHighPriority() {
        return (ULong) get(29);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerReadHighPriority(ULong value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public ULong getMinTimerReadHighPriority() {
        return (ULong) get(30);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerReadHighPriority(ULong value) {
        set(31, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public ULong getAvgTimerReadHighPriority() {
        return (ULong) get(31);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerReadHighPriority(ULong value) {
        set(32, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_HIGH_PRIORITY</code>.
     */
    public ULong getMaxTimerReadHighPriority() {
        return (ULong) get(32);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_NO_INSERT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountReadNoInsert(ULong value) {
        set(33, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_NO_INSERT</code>.
     */
    public ULong getCountReadNoInsert() {
        return (ULong) get(33);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_NO_INSERT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerReadNoInsert(ULong value) {
        set(34, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_NO_INSERT</code>.
     */
    public ULong getSumTimerReadNoInsert() {
        return (ULong) get(34);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_NO_INSERT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerReadNoInsert(ULong value) {
        set(35, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_NO_INSERT</code>.
     */
    public ULong getMinTimerReadNoInsert() {
        return (ULong) get(35);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_NO_INSERT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerReadNoInsert(ULong value) {
        set(36, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_NO_INSERT</code>.
     */
    public ULong getAvgTimerReadNoInsert() {
        return (ULong) get(36);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_NO_INSERT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerReadNoInsert(ULong value) {
        set(37, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_NO_INSERT</code>.
     */
    public ULong getMaxTimerReadNoInsert() {
        return (ULong) get(37);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_EXTERNAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountReadExternal(ULong value) {
        set(38, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_READ_EXTERNAL</code>.
     */
    public ULong getCountReadExternal() {
        return (ULong) get(38);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_EXTERNAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerReadExternal(ULong value) {
        set(39, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_READ_EXTERNAL</code>.
     */
    public ULong getSumTimerReadExternal() {
        return (ULong) get(39);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_EXTERNAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerReadExternal(ULong value) {
        set(40, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_READ_EXTERNAL</code>.
     */
    public ULong getMinTimerReadExternal() {
        return (ULong) get(40);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_EXTERNAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerReadExternal(ULong value) {
        set(41, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_READ_EXTERNAL</code>.
     */
    public ULong getAvgTimerReadExternal() {
        return (ULong) get(41);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_EXTERNAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerReadExternal(ULong value) {
        set(42, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_READ_EXTERNAL</code>.
     */
    public ULong getMaxTimerReadExternal() {
        return (ULong) get(42);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_ALLOW_WRITE</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountWriteAllowWrite(ULong value) {
        set(43, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_ALLOW_WRITE</code>.
     */
    public ULong getCountWriteAllowWrite() {
        return (ULong) get(43);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerWriteAllowWrite(ULong value) {
        set(44, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public ULong getSumTimerWriteAllowWrite() {
        return (ULong) get(44);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerWriteAllowWrite(ULong value) {
        set(45, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public ULong getMinTimerWriteAllowWrite() {
        return (ULong) get(45);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerWriteAllowWrite(ULong value) {
        set(46, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public ULong getAvgTimerWriteAllowWrite() {
        return (ULong) get(46);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerWriteAllowWrite(ULong value) {
        set(47, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_ALLOW_WRITE</code>.
     */
    public ULong getMaxTimerWriteAllowWrite() {
        return (ULong) get(47);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_CONCURRENT_INSERT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountWriteConcurrentInsert(ULong value) {
        set(48, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_CONCURRENT_INSERT</code>.
     */
    public ULong getCountWriteConcurrentInsert() {
        return (ULong) get(48);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerWriteConcurrentInsert(ULong value) {
        set(49, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public ULong getSumTimerWriteConcurrentInsert() {
        return (ULong) get(49);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerWriteConcurrentInsert(ULong value) {
        set(50, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public ULong getMinTimerWriteConcurrentInsert() {
        return (ULong) get(50);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerWriteConcurrentInsert(ULong value) {
        set(51, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public ULong getAvgTimerWriteConcurrentInsert() {
        return (ULong) get(51);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerWriteConcurrentInsert(ULong value) {
        set(52, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_CONCURRENT_INSERT</code>.
     */
    public ULong getMaxTimerWriteConcurrentInsert() {
        return (ULong) get(52);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_LOW_PRIORITY</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountWriteLowPriority(ULong value) {
        set(53, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_LOW_PRIORITY</code>.
     */
    public ULong getCountWriteLowPriority() {
        return (ULong) get(53);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerWriteLowPriority(ULong value) {
        set(54, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public ULong getSumTimerWriteLowPriority() {
        return (ULong) get(54);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerWriteLowPriority(ULong value) {
        set(55, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public ULong getMinTimerWriteLowPriority() {
        return (ULong) get(55);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerWriteLowPriority(ULong value) {
        set(56, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public ULong getAvgTimerWriteLowPriority() {
        return (ULong) get(56);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerWriteLowPriority(ULong value) {
        set(57, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_LOW_PRIORITY</code>.
     */
    public ULong getMaxTimerWriteLowPriority() {
        return (ULong) get(57);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_NORMAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountWriteNormal(ULong value) {
        set(58, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_NORMAL</code>.
     */
    public ULong getCountWriteNormal() {
        return (ULong) get(58);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_NORMAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerWriteNormal(ULong value) {
        set(59, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_NORMAL</code>.
     */
    public ULong getSumTimerWriteNormal() {
        return (ULong) get(59);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_NORMAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerWriteNormal(ULong value) {
        set(60, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_NORMAL</code>.
     */
    public ULong getMinTimerWriteNormal() {
        return (ULong) get(60);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_NORMAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerWriteNormal(ULong value) {
        set(61, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_NORMAL</code>.
     */
    public ULong getAvgTimerWriteNormal() {
        return (ULong) get(61);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_NORMAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerWriteNormal(ULong value) {
        set(62, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_NORMAL</code>.
     */
    public ULong getMaxTimerWriteNormal() {
        return (ULong) get(62);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_EXTERNAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setCountWriteExternal(ULong value) {
        set(63, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.COUNT_WRITE_EXTERNAL</code>.
     */
    public ULong getCountWriteExternal() {
        return (ULong) get(63);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_EXTERNAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setSumTimerWriteExternal(ULong value) {
        set(64, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.SUM_TIMER_WRITE_EXTERNAL</code>.
     */
    public ULong getSumTimerWriteExternal() {
        return (ULong) get(64);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_EXTERNAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMinTimerWriteExternal(ULong value) {
        set(65, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MIN_TIMER_WRITE_EXTERNAL</code>.
     */
    public ULong getMinTimerWriteExternal() {
        return (ULong) get(65);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_EXTERNAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setAvgTimerWriteExternal(ULong value) {
        set(66, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.AVG_TIMER_WRITE_EXTERNAL</code>.
     */
    public ULong getAvgTimerWriteExternal() {
        return (ULong) get(66);
    }

    /**
     * Setter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_EXTERNAL</code>.
     */
    public TableLockWaitsSummaryByTableRecord setMaxTimerWriteExternal(ULong value) {
        set(67, value);
        return this;
    }

    /**
     * Getter for
     * <code>performance_schema.table_lock_waits_summary_by_table.MAX_TIMER_WRITE_EXTERNAL</code>.
     */
    public ULong getMaxTimerWriteExternal() {
        return (ULong) get(67);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TableLockWaitsSummaryByTableRecord
     */
    public TableLockWaitsSummaryByTableRecord() {
        super(TableLockWaitsSummaryByTable.TABLE_LOCK_WAITS_SUMMARY_BY_TABLE);
    }

    /**
     * Create a detached, initialised TableLockWaitsSummaryByTableRecord
     */
    public TableLockWaitsSummaryByTableRecord(String objectType, String objectSchema, String objectName, ULong countStar, ULong sumTimerWait, ULong minTimerWait, ULong avgTimerWait, ULong maxTimerWait, ULong countRead, ULong sumTimerRead, ULong minTimerRead, ULong avgTimerRead, ULong maxTimerRead, ULong countWrite, ULong sumTimerWrite, ULong minTimerWrite, ULong avgTimerWrite, ULong maxTimerWrite, ULong countReadNormal, ULong sumTimerReadNormal, ULong minTimerReadNormal, ULong avgTimerReadNormal, ULong maxTimerReadNormal, ULong countReadWithSharedLocks, ULong sumTimerReadWithSharedLocks, ULong minTimerReadWithSharedLocks, ULong avgTimerReadWithSharedLocks, ULong maxTimerReadWithSharedLocks, ULong countReadHighPriority, ULong sumTimerReadHighPriority, ULong minTimerReadHighPriority, ULong avgTimerReadHighPriority, ULong maxTimerReadHighPriority, ULong countReadNoInsert, ULong sumTimerReadNoInsert, ULong minTimerReadNoInsert, ULong avgTimerReadNoInsert, ULong maxTimerReadNoInsert, ULong countReadExternal, ULong sumTimerReadExternal, ULong minTimerReadExternal, ULong avgTimerReadExternal, ULong maxTimerReadExternal, ULong countWriteAllowWrite, ULong sumTimerWriteAllowWrite, ULong minTimerWriteAllowWrite, ULong avgTimerWriteAllowWrite, ULong maxTimerWriteAllowWrite, ULong countWriteConcurrentInsert, ULong sumTimerWriteConcurrentInsert, ULong minTimerWriteConcurrentInsert, ULong avgTimerWriteConcurrentInsert, ULong maxTimerWriteConcurrentInsert, ULong countWriteLowPriority, ULong sumTimerWriteLowPriority, ULong minTimerWriteLowPriority, ULong avgTimerWriteLowPriority, ULong maxTimerWriteLowPriority, ULong countWriteNormal, ULong sumTimerWriteNormal, ULong minTimerWriteNormal, ULong avgTimerWriteNormal, ULong maxTimerWriteNormal, ULong countWriteExternal, ULong sumTimerWriteExternal, ULong minTimerWriteExternal, ULong avgTimerWriteExternal, ULong maxTimerWriteExternal) {
        super(TableLockWaitsSummaryByTable.TABLE_LOCK_WAITS_SUMMARY_BY_TABLE);

        setObjectType(objectType);
        setObjectSchema(objectSchema);
        setObjectName(objectName);
        setCountStar(countStar);
        setSumTimerWait(sumTimerWait);
        setMinTimerWait(minTimerWait);
        setAvgTimerWait(avgTimerWait);
        setMaxTimerWait(maxTimerWait);
        setCountRead(countRead);
        setSumTimerRead(sumTimerRead);
        setMinTimerRead(minTimerRead);
        setAvgTimerRead(avgTimerRead);
        setMaxTimerRead(maxTimerRead);
        setCountWrite(countWrite);
        setSumTimerWrite(sumTimerWrite);
        setMinTimerWrite(minTimerWrite);
        setAvgTimerWrite(avgTimerWrite);
        setMaxTimerWrite(maxTimerWrite);
        setCountReadNormal(countReadNormal);
        setSumTimerReadNormal(sumTimerReadNormal);
        setMinTimerReadNormal(minTimerReadNormal);
        setAvgTimerReadNormal(avgTimerReadNormal);
        setMaxTimerReadNormal(maxTimerReadNormal);
        setCountReadWithSharedLocks(countReadWithSharedLocks);
        setSumTimerReadWithSharedLocks(sumTimerReadWithSharedLocks);
        setMinTimerReadWithSharedLocks(minTimerReadWithSharedLocks);
        setAvgTimerReadWithSharedLocks(avgTimerReadWithSharedLocks);
        setMaxTimerReadWithSharedLocks(maxTimerReadWithSharedLocks);
        setCountReadHighPriority(countReadHighPriority);
        setSumTimerReadHighPriority(sumTimerReadHighPriority);
        setMinTimerReadHighPriority(minTimerReadHighPriority);
        setAvgTimerReadHighPriority(avgTimerReadHighPriority);
        setMaxTimerReadHighPriority(maxTimerReadHighPriority);
        setCountReadNoInsert(countReadNoInsert);
        setSumTimerReadNoInsert(sumTimerReadNoInsert);
        setMinTimerReadNoInsert(minTimerReadNoInsert);
        setAvgTimerReadNoInsert(avgTimerReadNoInsert);
        setMaxTimerReadNoInsert(maxTimerReadNoInsert);
        setCountReadExternal(countReadExternal);
        setSumTimerReadExternal(sumTimerReadExternal);
        setMinTimerReadExternal(minTimerReadExternal);
        setAvgTimerReadExternal(avgTimerReadExternal);
        setMaxTimerReadExternal(maxTimerReadExternal);
        setCountWriteAllowWrite(countWriteAllowWrite);
        setSumTimerWriteAllowWrite(sumTimerWriteAllowWrite);
        setMinTimerWriteAllowWrite(minTimerWriteAllowWrite);
        setAvgTimerWriteAllowWrite(avgTimerWriteAllowWrite);
        setMaxTimerWriteAllowWrite(maxTimerWriteAllowWrite);
        setCountWriteConcurrentInsert(countWriteConcurrentInsert);
        setSumTimerWriteConcurrentInsert(sumTimerWriteConcurrentInsert);
        setMinTimerWriteConcurrentInsert(minTimerWriteConcurrentInsert);
        setAvgTimerWriteConcurrentInsert(avgTimerWriteConcurrentInsert);
        setMaxTimerWriteConcurrentInsert(maxTimerWriteConcurrentInsert);
        setCountWriteLowPriority(countWriteLowPriority);
        setSumTimerWriteLowPriority(sumTimerWriteLowPriority);
        setMinTimerWriteLowPriority(minTimerWriteLowPriority);
        setAvgTimerWriteLowPriority(avgTimerWriteLowPriority);
        setMaxTimerWriteLowPriority(maxTimerWriteLowPriority);
        setCountWriteNormal(countWriteNormal);
        setSumTimerWriteNormal(sumTimerWriteNormal);
        setMinTimerWriteNormal(minTimerWriteNormal);
        setAvgTimerWriteNormal(avgTimerWriteNormal);
        setMaxTimerWriteNormal(maxTimerWriteNormal);
        setCountWriteExternal(countWriteExternal);
        setSumTimerWriteExternal(sumTimerWriteExternal);
        setMinTimerWriteExternal(minTimerWriteExternal);
        setAvgTimerWriteExternal(avgTimerWriteExternal);
        setMaxTimerWriteExternal(maxTimerWriteExternal);
    }

    /**
     * Create a detached, initialised TableLockWaitsSummaryByTableRecord
     */
    public TableLockWaitsSummaryByTableRecord(com.neurasim.jooq.performance_schema.tables.pojos.TableLockWaitsSummaryByTable value) {
        super(TableLockWaitsSummaryByTable.TABLE_LOCK_WAITS_SUMMARY_BY_TABLE);

        if (value != null) {
            setObjectType(value.getObjectType());
            setObjectSchema(value.getObjectSchema());
            setObjectName(value.getObjectName());
            setCountStar(value.getCountStar());
            setSumTimerWait(value.getSumTimerWait());
            setMinTimerWait(value.getMinTimerWait());
            setAvgTimerWait(value.getAvgTimerWait());
            setMaxTimerWait(value.getMaxTimerWait());
            setCountRead(value.getCountRead());
            setSumTimerRead(value.getSumTimerRead());
            setMinTimerRead(value.getMinTimerRead());
            setAvgTimerRead(value.getAvgTimerRead());
            setMaxTimerRead(value.getMaxTimerRead());
            setCountWrite(value.getCountWrite());
            setSumTimerWrite(value.getSumTimerWrite());
            setMinTimerWrite(value.getMinTimerWrite());
            setAvgTimerWrite(value.getAvgTimerWrite());
            setMaxTimerWrite(value.getMaxTimerWrite());
            setCountReadNormal(value.getCountReadNormal());
            setSumTimerReadNormal(value.getSumTimerReadNormal());
            setMinTimerReadNormal(value.getMinTimerReadNormal());
            setAvgTimerReadNormal(value.getAvgTimerReadNormal());
            setMaxTimerReadNormal(value.getMaxTimerReadNormal());
            setCountReadWithSharedLocks(value.getCountReadWithSharedLocks());
            setSumTimerReadWithSharedLocks(value.getSumTimerReadWithSharedLocks());
            setMinTimerReadWithSharedLocks(value.getMinTimerReadWithSharedLocks());
            setAvgTimerReadWithSharedLocks(value.getAvgTimerReadWithSharedLocks());
            setMaxTimerReadWithSharedLocks(value.getMaxTimerReadWithSharedLocks());
            setCountReadHighPriority(value.getCountReadHighPriority());
            setSumTimerReadHighPriority(value.getSumTimerReadHighPriority());
            setMinTimerReadHighPriority(value.getMinTimerReadHighPriority());
            setAvgTimerReadHighPriority(value.getAvgTimerReadHighPriority());
            setMaxTimerReadHighPriority(value.getMaxTimerReadHighPriority());
            setCountReadNoInsert(value.getCountReadNoInsert());
            setSumTimerReadNoInsert(value.getSumTimerReadNoInsert());
            setMinTimerReadNoInsert(value.getMinTimerReadNoInsert());
            setAvgTimerReadNoInsert(value.getAvgTimerReadNoInsert());
            setMaxTimerReadNoInsert(value.getMaxTimerReadNoInsert());
            setCountReadExternal(value.getCountReadExternal());
            setSumTimerReadExternal(value.getSumTimerReadExternal());
            setMinTimerReadExternal(value.getMinTimerReadExternal());
            setAvgTimerReadExternal(value.getAvgTimerReadExternal());
            setMaxTimerReadExternal(value.getMaxTimerReadExternal());
            setCountWriteAllowWrite(value.getCountWriteAllowWrite());
            setSumTimerWriteAllowWrite(value.getSumTimerWriteAllowWrite());
            setMinTimerWriteAllowWrite(value.getMinTimerWriteAllowWrite());
            setAvgTimerWriteAllowWrite(value.getAvgTimerWriteAllowWrite());
            setMaxTimerWriteAllowWrite(value.getMaxTimerWriteAllowWrite());
            setCountWriteConcurrentInsert(value.getCountWriteConcurrentInsert());
            setSumTimerWriteConcurrentInsert(value.getSumTimerWriteConcurrentInsert());
            setMinTimerWriteConcurrentInsert(value.getMinTimerWriteConcurrentInsert());
            setAvgTimerWriteConcurrentInsert(value.getAvgTimerWriteConcurrentInsert());
            setMaxTimerWriteConcurrentInsert(value.getMaxTimerWriteConcurrentInsert());
            setCountWriteLowPriority(value.getCountWriteLowPriority());
            setSumTimerWriteLowPriority(value.getSumTimerWriteLowPriority());
            setMinTimerWriteLowPriority(value.getMinTimerWriteLowPriority());
            setAvgTimerWriteLowPriority(value.getAvgTimerWriteLowPriority());
            setMaxTimerWriteLowPriority(value.getMaxTimerWriteLowPriority());
            setCountWriteNormal(value.getCountWriteNormal());
            setSumTimerWriteNormal(value.getSumTimerWriteNormal());
            setMinTimerWriteNormal(value.getMinTimerWriteNormal());
            setAvgTimerWriteNormal(value.getAvgTimerWriteNormal());
            setMaxTimerWriteNormal(value.getMaxTimerWriteNormal());
            setCountWriteExternal(value.getCountWriteExternal());
            setSumTimerWriteExternal(value.getSumTimerWriteExternal());
            setMinTimerWriteExternal(value.getMinTimerWriteExternal());
            setAvgTimerWriteExternal(value.getAvgTimerWriteExternal());
            setMaxTimerWriteExternal(value.getMaxTimerWriteExternal());
        }
    }
}
