/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.information_schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EnabledRoles implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String roleName;
    private final String roleHost;
    private final String isDefault;
    private final String isMandatory;

    public EnabledRoles(EnabledRoles value) {
        this.roleName = value.roleName;
        this.roleHost = value.roleHost;
        this.isDefault = value.isDefault;
        this.isMandatory = value.isMandatory;
    }

    public EnabledRoles(
        String roleName,
        String roleHost,
        String isDefault,
        String isMandatory
    ) {
        this.roleName = roleName;
        this.roleHost = roleHost;
        this.isDefault = isDefault;
        this.isMandatory = isMandatory;
    }

    /**
     * Getter for <code>information_schema.ENABLED_ROLES.ROLE_NAME</code>.
     */
    public String getRoleName() {
        return this.roleName;
    }

    /**
     * Getter for <code>information_schema.ENABLED_ROLES.ROLE_HOST</code>.
     */
    public String getRoleHost() {
        return this.roleHost;
    }

    /**
     * Getter for <code>information_schema.ENABLED_ROLES.IS_DEFAULT</code>.
     */
    public String getIsDefault() {
        return this.isDefault;
    }

    /**
     * Getter for <code>information_schema.ENABLED_ROLES.IS_MANDATORY</code>.
     */
    public String getIsMandatory() {
        return this.isMandatory;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final EnabledRoles other = (EnabledRoles) obj;
        if (this.roleName == null) {
            if (other.roleName != null)
                return false;
        }
        else if (!this.roleName.equals(other.roleName))
            return false;
        if (this.roleHost == null) {
            if (other.roleHost != null)
                return false;
        }
        else if (!this.roleHost.equals(other.roleHost))
            return false;
        if (this.isDefault == null) {
            if (other.isDefault != null)
                return false;
        }
        else if (!this.isDefault.equals(other.isDefault))
            return false;
        if (this.isMandatory == null) {
            if (other.isMandatory != null)
                return false;
        }
        else if (!this.isMandatory.equals(other.isMandatory))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.roleName == null) ? 0 : this.roleName.hashCode());
        result = prime * result + ((this.roleHost == null) ? 0 : this.roleHost.hashCode());
        result = prime * result + ((this.isDefault == null) ? 0 : this.isDefault.hashCode());
        result = prime * result + ((this.isMandatory == null) ? 0 : this.isMandatory.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EnabledRoles (");

        sb.append(roleName);
        sb.append(", ").append(roleHost);
        sb.append(", ").append(isDefault);
        sb.append(", ").append(isMandatory);

        sb.append(")");
        return sb.toString();
    }
}
