/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.information_schema.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InnodbFields implements Serializable {

    private static final long serialVersionUID = 1L;

    private final byte[] indexId;
    private final String name;
    private final ULong pos;

    public InnodbFields(InnodbFields value) {
        this.indexId = value.indexId;
        this.name = value.name;
        this.pos = value.pos;
    }

    public InnodbFields(
        byte[] indexId,
        String name,
        ULong pos
    ) {
        this.indexId = indexId;
        this.name = name;
        this.pos = pos;
    }

    /**
     * Getter for <code>information_schema.INNODB_FIELDS.INDEX_ID</code>.
     */
    public byte[] getIndexId() {
        return this.indexId;
    }

    /**
     * Getter for <code>information_schema.INNODB_FIELDS.NAME</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>information_schema.INNODB_FIELDS.POS</code>.
     */
    public ULong getPos() {
        return this.pos;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final InnodbFields other = (InnodbFields) obj;
        if (this.indexId == null) {
            if (other.indexId != null)
                return false;
        }
        else if (!Arrays.equals(this.indexId, other.indexId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.pos == null) {
            if (other.pos != null)
                return false;
        }
        else if (!this.pos.equals(other.pos))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.indexId == null) ? 0 : Arrays.hashCode(this.indexId));
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.pos == null) ? 0 : this.pos.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InnodbFields (");

        sb.append("[binary...]");
        sb.append(", ").append(name);
        sb.append(", ").append(pos);

        sb.append(")");
        return sb.toString();
    }
}
