/*
 * This file is generated by jOOQ.
 */
package com.neurasim.jooq.information_schema.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAttributes implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String user;
    private final String host;
    private final String attribute;

    public UserAttributes(UserAttributes value) {
        this.user = value.user;
        this.host = value.host;
        this.attribute = value.attribute;
    }

    public UserAttributes(
        String user,
        String host,
        String attribute
    ) {
        this.user = user;
        this.host = host;
        this.attribute = attribute;
    }

    /**
     * Getter for <code>information_schema.USER_ATTRIBUTES.USER</code>.
     */
    public String getUser() {
        return this.user;
    }

    /**
     * Getter for <code>information_schema.USER_ATTRIBUTES.HOST</code>.
     */
    public String getHost() {
        return this.host;
    }

    /**
     * Getter for <code>information_schema.USER_ATTRIBUTES.ATTRIBUTE</code>.
     */
    public String getAttribute() {
        return this.attribute;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserAttributes other = (UserAttributes) obj;
        if (this.user == null) {
            if (other.user != null)
                return false;
        }
        else if (!this.user.equals(other.user))
            return false;
        if (this.host == null) {
            if (other.host != null)
                return false;
        }
        else if (!this.host.equals(other.host))
            return false;
        if (this.attribute == null) {
            if (other.attribute != null)
                return false;
        }
        else if (!this.attribute.equals(other.attribute))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.user == null) ? 0 : this.user.hashCode());
        result = prime * result + ((this.host == null) ? 0 : this.host.hashCode());
        result = prime * result + ((this.attribute == null) ? 0 : this.attribute.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAttributes (");

        sb.append(user);
        sb.append(", ").append(host);
        sb.append(", ").append(attribute);

        sb.append(")");
        return sb.toString();
    }
}
